# Generated by Django 4.2.3 on 2023-07-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_article_banner"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["id"], name="id_index"),
        ),
    ]
